### ISSUE TITLE
Copy last entry, "i" or "o" and insert the opposite with the same time, i.e. "o" or "i"

### ISSUE THREAD

**Issue by artkpv** [jupj/vim-timeclock#2]
Copy last entry, "i" or "o" and insert the opposite with the same time, i.e. "o" or "i". Example 

Have:
```
o 2024-10-23 19:24
```

Final:
```
o 2024-10-23 19:24
i 2024-10-23 19:24
```

**Comment by jupj** [comment]
Thanks for the input.

We already have something like this - the `:TimeclockSwitch {timestamp}` command appends an "o" line followed by an "i" line to the end of the file, both lines have the same timestamp. This is currently mapped to `<LocalLeader>s`.

While the `:TimeclockSwitch` command works, I'm not super happy about it. The jump between command mode and insert mode breaks the flow. My initial thoughts about making a copy, as described above, are similar - it seems to break the flow.

It would be nice to be able switch tasks directly in insert mode without having to jump out to normal mode or command mode. Maybe mapping a short-cut in insert mode for the copy operation, or making omni-completion at the beginning of a line so that it auto-completes the opposite i/o + timestamp from the previous i/o line. Completion could also list the current time as an alternative, in addition to the timestamp from the previous line.

@artkpv thoughts?

**Comment by jupj** [comment]
I modified `:TimeclockSwitch` (and `:TimeclockIn`) so that they start insert mode automatically after inserting the entries.

This improves the flow when switching tasks: press `<LocalLeader>s`, update timestamp on command line, press enter. This insert an "o" entry followed by an "i" entry with the given timestamp, and leaves the user in insert mode ready to enter the task/account.

EDIT: typos

**Comment by artkpv** [comment]
> We already have something like this - the :TimeclockSwitch {timestamp} command appends an "o" line followed by an "i" line to the end of the file, both lines have the same timestamp. This is currently mapped to <LocalLeader>s.

Thank you for your answer and the update for the insert mode when pressing <localLeader>i.

However, fixing the date each time I insert a new entry to match the last one is more typing than copying the last enty's time.

**Comment by jupj** [comment]
Thanks for the clarification. Now I understand better the need for making a copy with the opposite "i/o".

**Comment by jupj** [comment]
Added the `:TimeclockCopy` command with mapping `<LocalLeader>c`.

@artkpv feel free to reopen this issue if I missed something.

**Comment by artkpv** [comment]
@jupj  Thank you, that works :+1:
